### ISSUE TITLE
想问下fasthttp的这个问题

### ISSUE THREAD

**Issue by molizz** [insionng/vodka#3]
https://github.com/insionng/vodka/blob/9202e093f9a53f71149589bd1dd9ddbc5a607497/engine/fasthttp/request.go#L122

这行代码中
```
 r.Request.Body()
```
这个返回的是[]byte ，如果是很大的文件POST上来，会不会造成内存不足呢？

谢谢

**Comment by insionng** [comment]
前端一般是经过nginx代理来控制提交的文件大小，太大的文件首先在nginx就被过滤了。不建议用作大文件存储，大文件会可能造成服务阻塞，如果不考虑云产品的话，可以用类似minio搭建私有文件存储服务。
